# Generated by Django 5.0.6 on 2024-08-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banner_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
