# Generated by Django 5.0.6 on 2024-08-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='form',
            name='name',
        ),
        migrations.RemoveField(
            model_name='form',
            name='subject',
        ),
        migrations.AddField(
            model_name='form',
            name='ism',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='text',
            field=models.TextField(),
        ),
    ]
