# Generated by Django 5.0.6 on 2024-08-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_form_last_name_remove_form_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='familiya',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
