# Generated by Django 5.0.6 on 2024-08-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
